# Generated by Django 2.2.9 on 2020-01-26 09:48

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('RDE', '0003_auto_20200124_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdepage',
            name='content',
            field=wagtail.core.fields.StreamField([('courses', wagtail.core.blocks.StructBlock([('points', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('point', wagtail.core.blocks.CharBlock(max_length=200, required=True)), ('url', wagtail.core.blocks.URLBlock(required=True))])))])), ('essays', wagtail.core.blocks.StructBlock([('points', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('point', wagtail.core.blocks.CharBlock(max_length=200, required=True)), ('url', wagtail.core.blocks.URLBlock(required=True))])))])), ('materials', wagtail.core.blocks.StructBlock([('points', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('point', wagtail.core.blocks.CharBlock(max_length=200, required=True)), ('url', wagtail.core.blocks.URLBlock(required=True))])))])), ('links', wagtail.core.blocks.StructBlock([('points', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('point', wagtail.core.blocks.CharBlock(max_length=200, required=True)), ('url', wagtail.core.blocks.URLBlock(required=True))])))]))], blank=True, null=True),
        ),
    ]
