# Generated by Django 2.2.9 on 2020-01-26 11:14

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('RDE', '0005_auto_20200126_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdepage',
            name='content',
            field=wagtail.core.fields.StreamField([('courses', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=True)), ('points_c', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('point_c', wagtail.core.blocks.CharBlock(max_length=200, required=True)), ('url_c', wagtail.core.blocks.URLBlock(required=True))])))])), ('essays', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=True)), ('points_e', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('point_e', wagtail.core.blocks.CharBlock(max_length=200, required=True)), ('url_e', wagtail.core.blocks.URLBlock(required=True))])))])), ('materials', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=True)), ('points_m', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('point_m', wagtail.core.blocks.CharBlock(max_length=200, required=True)), ('url_m', wagtail.core.blocks.URLBlock(required=True))])))])), ('links', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=True)), ('points_l', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('point_l', wagtail.core.blocks.CharBlock(max_length=200, required=True)), ('url_l', wagtail.core.blocks.URLBlock(required=True))])))]))], blank=True, null=True),
        ),
    ]
