# Generated by Django 2.2.9 on 2020-01-26 11:45

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('RDE', '0006_auto_20200126_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdepage',
            name='content',
            field=wagtail.core.fields.StreamField([('resources', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=True)), ('points_c', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('point_c', wagtail.core.blocks.CharBlock(max_length=200, required=True)), ('url_c', wagtail.core.blocks.URLBlock(required=True))])))]))], blank=True, null=True),
        ),
    ]
