# Generated by Django 2.2.9 on 2020-01-21 06:44

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('GR', '0006_auto_20200120_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grpage',
            name='content',
        ),
        migrations.AddField(
            model_name='grpage',
            name='content1',
            field=wagtail.core.fields.StreamField([('main', wagtail.core.blocks.StructBlock([('points', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('point', wagtail.core.blocks.CharBlock(max_length=200, required=True)), ('pdfs', wagtail.core.blocks.ListBlock(wagtail.documents.blocks.DocumentChooserBlock(required=True)))])))]))], null=True),
        ),
        migrations.AddField(
            model_name='grpage',
            name='content2',
            field=wagtail.core.fields.StreamField([('related', wagtail.core.blocks.StructBlock([('points', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('point', wagtail.core.blocks.CharBlock(max_length=200, required=True)), ('pdfs', wagtail.core.blocks.ListBlock(wagtail.documents.blocks.DocumentChooserBlock(required=True)))])))]))], null=True),
        ),
    ]
